version: '2'
services:
  app:
    container_name: app
    build: coffeemaker
    ports:
      - "5000:5000"
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_HOSTNAME=app_db
      - DB_PORT=5432
      - DB_NAME=coffe_maker
      - RABBITMQ_ADDRESS=app_rabbit
      - RABBITMQ_USERNAME=root
      - RABBITMQ_USER_PASSWORD=root
      - RABBITMQ_PORT=5672
    depends_on:
      - "app_db"
      - "app_rabbit"
    links:
      - "app_db"
      - "app_rabbit"
  web:
    container_name: web
    build: coffeemaker-web
    ports:
      - "3000:3000"
    environment:
      - API_HOSTNAME=app
      - API_PORT=5000
    depends_on:
      - "app"
    links:
      - "app"
  app_db:
    container_name: app_db
    ports:
      - "5432:5432"
    image: "postgres:14.1-alpine"
    volumes:
       - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=coffe_maker
  app_rabbit:
    container_name: app_rabbit
    image: "rabbitmq:3.7.5-management"
    ports:
      - "5672:5672"
      - "8088:15672"
    environment:
      RABBITMQ_DEFAULT_PASS: "root"
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_VHOST: "/"
volumes:
  db:
    driver: local